create or replace synonym SCHEMA_VERSION for KORREKSJON.SCHEMA_VERSION;
create or replace synonym PERSISTENT_PROPERTY for KORREKSJON.PERSISTENT_PROPERTY;
create or replace synonym PERSISTENT_PROP_ENDRINGSLOGG for KORREKSJON.PERSISTENT_PROP_ENDRINGSLOGG;
create or replace synonym SEQUENCE_NUMBER for KORREKSJON.SEQUENCE_NUMBER;
create or replace synonym KORREKSJON for KORREKSJON.KORREKSJON;
create or replace synonym KORREKSJON_SEQUENCE for KORREKSJON.KORREKSJON_SEQUENCE;
