
-- log on as KORREKSJON
drop table SEQUENCE_NUMBER cascade constraints;

drop table PERSISTENT_PROP_ENDRINGSLOGG;

-- No longer in use
drop sequence KORREKSJON_SEQUENCE;

--drop table KORREKSJON_BACKUP_VERSJON_10  cascade constraints;

alter table
   korreksjon
rename to
   KORREKSJON_BACKUP_VERSJON_10;

WHENEVER SQLERROR EXIT SQL.SQLCODE ;

CREATE TABLE KORR_TILSTANDER (
   ID number(19,0) PRIMARY KEY NOT NULL,
   KORREKSJON_ID number(19,0) NOT NULL,
   SOURCE varchar2(255 char) NOT NULL,
   KORREKSJON_TYPE varchar2(255 char),
   BESTILLINGSNUMMER varchar2(255 char) NOT NULL,
   BESTILLINGSDATO date NOT NULL,
   CREATED_AT timestamp NOT NULL,
   CREATED_BY_USER varchar2(255) NOT NULL,
   STATUS varchar2(255 char) NOT NULL,
   DEBET_ACCOUNT varchar2(255 char),
   CREDIT_ACCOUNT varchar2(255 char),
   DEBET_NAVN varchar2(255 char),
   AMOUNT number(19,2),
   OPPRINNELIG_DATO date,
   CAUSE varchar2(255 char),
   BLANKETTNUMMER varchar2(255 char),
   FRITEKST varchar2(255 char),
   GEBYR_BANKREGNUMMER varchar2(255 char),
   ARKIVREF varchar2(255 char),
   BESTILLING_STATUS_UPDATE_PATH varchar2(255 char),
   BUNTNUMMER varchar2(255 char),
   KID_NUMMER varchar2(255 char),
   TRANSTEKST varchar2(255 char),
   NIBE_BUS_KODE varchar2(15 char),
   NIBE_ALC_KODE varchar2(15 char),
   BELOP_KREDIT_SUMPOST number(19,2),
   IDX number(10,0)
);
CREATE INDEX KORR_TILSTANDER_STATUS_IDX ON KORR_TILSTANDER(STATUS);
CREATE INDEX KORR_TILSTANDER_TYPE_IDX ON KORR_TILSTANDER(KORREKSJON_TYPE);


CREATE TABLE KORREKSJON (
   ID number(19,0) PRIMARY KEY NOT NULL,
   OBJECT_TYPE varchar2(255) NOT NULL,
   SOURCE varchar2(255) NOT NULL,
   BESTILLINGSNUMMER varchar2(255) NOT NULL,
   BESTILLINGSDATO date NOT NULL,
   KORREKSJON_TYPE varchar2(255),
   STATUS varchar2(255) NOT NULL,
   VERSION number (10,0) DEFAULT 0,
   CURRENT_TILSTAND_ID number(19,0),
   REVERSERING_ID number(19,0),
   OVERFORING_ID number(19,0),
   BESTILLING_ID number(19,0)
);
alter table KORREKSJON  add constraint FK_CURR_TILSTAND foreign key (CURRENT_TILSTAND_ID) REFERENCING KORR_TILSTANDER(ID);
alter table KORREKSJON  add constraint FK_OVERFORING foreign key (OVERFORING_ID) REFERENCING KORREKSJON(ID);
alter table KORREKSJON  add constraint FK_REVERSERING foreign key (REVERSERING_ID) REFERENCING KORREKSJON(ID);

drop index KORREKSJON_STATUS_IDX;
drop index KORREKSJON_TYPE_IDX;

CREATE INDEX KORRE_BEST_NR_IDX ON KORREKSJON(BESTILLINGSNUMMER);
CREATE INDEX KORRE_DATO_IDX ON KORREKSJON(BESTILLINGSDATO);
CREATE INDEX KORREKSJON_STATUS_IDX ON KORREKSJON(STATUS);
CREATE INDEX KORREKSJON_OBJECT_TYPE_IDX ON KORREKSJON(OBJECT_TYPE);
CREATE INDEX KORREKSJON_TYPE_IDX ON KORREKSJON(KORREKSJON_TYPE);

