-- legg til ny kolonne i korreksjon
ALTER TABLE KORREKSJON ADD REVERSERING_MED_FULLMAKT_ID NUMBER(19,0) NULL ;

-- legg til foreign key referanse
ALTER TABLE KORREKSJON ADD CONSTRAINT FK_REVERSERING_FULLMAKT foreign key (REVERSERING_MED_FULLMAKT_ID) REFERENCING KORREKSJON(ID);

-- legg til unique constraint
ALTER TABLE KORR_TILSTANDER ADD CONSTRAINt UNIQUE_KORREKSJON unique (KORREKSJON_TYPE, BESTILLINGSNUMMER, BESTILLINGSDATO, STATUS);