CREATE TABLE "KORREKSJON"."FIL"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   CONTENT_LENGTH decimal(19),
   FILE_NAME varchar2(255),
   FILE_TYPE varchar2(255),
   ENCODING varchar2(255),
   STATUS_CODE varchar2(255),
   STATUS_HISTORY decimal(19)
)
;
CREATE UNIQUE INDEX PK_FIL ON "KORREKSJON"."FIL"(ID)
;
CREATE UNIQUE INDEX UNIQUE_STATUS_HISTORY ON "KORREKSJON"."FIL"(STATUS_HISTORY)
;
CREATE TABLE "KORREKSJON"."FILCONTENT"
(
   FIL_ID decimal(19) PRIMARY KEY NOT NULL,
   CONTENT blob,
   COMPRESSION varchar2(255)
)
;
CREATE UNIQUE INDEX PK_FIL_ID ON "KORREKSJON"."FILCONTENT"(FIL_ID)
;
CREATE TABLE "KORREKSJON"."KORREKSJON"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   KORREKSJON_TYPE varchar2(255) NOT NULL,
   BESTILLINGSNUMMER varchar2(255) NOT NULL,
   BESTILLINGSDATO timestamp NOT NULL,
   CREATED_AT timestamp NOT NULL,
   CREATED_BY_USER varchar2(255) NOT NULL,
   STATUS varchar2(255) NOT NULL,
   DEBET_ACCOUNT varchar2(255) NOT NULL,
   CREDIT_ACCOUNT varchar2(255) NOT NULL,
   AMOUNT decimal(19) NOT NULL,
   OPPRINNELIG_DATO timestamp NOT NULL,
   CAUSE varchar2(255) NOT NULL,
   FRITEKST varchar2(255),
   GEBYR_BANKREGNUMMER varchar2(255),
   ARKIVREF varchar2(255) NOT NULL,
   BLANKETTNUMMER varchar2(255) NOT NULL,
   SOURCE varchar2(255) DEFAULT 'KORREKSJON_WEB'  NOT NULL,
   BEST_STATUS_PATH varchar2(255),
   BUNTNUMMER varchar2(255),
   KID varchar2(255),
   TRANSTEKST varchar2(255),
   NIBE_BUS_KODE varchar2(15),
   NIBE_ALC_KODE varchar2(15),
   BELOP_KREDIT_SUMPOST decimal(19),
   ORIGINAL_ID decimal(19) NOT NULL,
   FORRIGE_ID decimal(19),
   NESTE_ID decimal(19)
)
;
ALTER TABLE "KORREKSJON"."KORREKSJON"
ADD CONSTRAINT FK_ORIGINAL_KORR
FOREIGN KEY (ORIGINAL_ID)
REFERENCES "KORREKSJON"."KORREKSJON"(ORIGINAL_ID)
;
ALTER TABLE "KORREKSJON"."KORREKSJON"
ADD CONSTRAINT FK_FORRIGE_KORR
FOREIGN KEY (FORRIGE_ID)
REFERENCES "KORREKSJON"."KORREKSJON"(FORRIGE_ID)
;
ALTER TABLE "KORREKSJON"."KORREKSJON"
ADD CONSTRAINT FK_NESTE_KORR
FOREIGN KEY (NESTE_ID)
REFERENCES "KORREKSJON"."KORREKSJON"(NESTE_ID)
;
CREATE INDEX KORR_CREATED_AT_IDX ON "KORREKSJON"."KORREKSJON"(CREATED_AT)
;
CREATE INDEX KORREKSJON_TYPE_IDX ON "KORREKSJON"."KORREKSJON"(KORREKSJON_TYPE)
;
CREATE INDEX KORREKSJON_GROUP_ID_IDX ON "KORREKSJON"."KORREKSJON"
(
  BESTILLINGSNUMMER,
  BESTILLINGSDATO
)
;
CREATE INDEX KORR_BESTILLINGSNUMMER_IDX ON "KORREKSJON"."KORREKSJON"(BESTILLINGSNUMMER)
;
CREATE INDEX KORR_SUCCESSOR_IDX ON "KORREKSJON"."KORREKSJON"(FORRIGE_ID)
;
CREATE INDEX KORREKSJON_STATUS_IDX ON "KORREKSJON"."KORREKSJON"(STATUS)
;
CREATE INDEX KORREKSJON_ENTITY_ID_IDX ON "KORREKSJON"."KORREKSJON"
(
  KORREKSJON_TYPE,
  BESTILLINGSNUMMER,
  BESTILLINGSDATO
)
;
CREATE UNIQUE INDEX UNIQUE_KORR_ID ON "KORREKSJON"."KORREKSJON"
(
  ORIGINAL_ID,
  FORRIGE_ID
)
;
CREATE INDEX KORR_BESTILLINGSDATO_IDX ON "KORREKSJON"."KORREKSJON"(BESTILLINGSDATO)
;
CREATE UNIQUE INDEX UNIQUE_KORREKSJON ON "KORREKSJON"."KORREKSJON"
(
  KORREKSJON_TYPE,
  BESTILLINGSNUMMER,
  BESTILLINGSDATO,
  STATUS
)
;
CREATE UNIQUE INDEX PK_KORREKSJON ON "KORREKSJON"."KORREKSJON"(ID)
;
CREATE TABLE "KORREKSJON"."PERSISTENT_PROP_ENDRINGSLOGG"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   KEY varchar2(255),
   SERVER varchar2(255),
   OLDVALUE varchar2(255),
   NEWVALUE varchar2(255),
   TID timestamp,
   USERNAME varchar2(255)
)
;
CREATE UNIQUE INDEX PK_PERS_PROP_ENDRINGSLOGG_547 ON "KORREKSJON"."PERSISTENT_PROP_ENDRINGSLOGG"(ID)
;
CREATE TABLE "KORREKSJON"."PERSISTENT_PROPERTY"
(
   KEY varchar2(255) NOT NULL,
   VALUE varchar2(255) NOT NULL,
   SERVER varchar2(255) DEFAULT 'all'
)
;
CREATE UNIQUE INDEX SYS_C004195 ON "KORREKSJON"."PERSISTENT_PROPERTY"
(
  KEY,
  SERVER
)
;
CREATE TABLE "KORREKSJON"."QOS_DATA"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   REFERANCE_ENTITY_CLASS varchar2(255),
   REFERANCE_ENTITY_ID decimal(19),
   QOS_STATUS_EVENT_CODE varchar2(255),
   TIME_RECEIVED timestamp,
   TIME_SENT timestamp,
   SYSTEM_OF_ORIGIN varchar2(255),
   NIM_QOS_TABLE_NAME varchar2(255),
   NIM_QOS_DATA varchar2(255)
)
;
CREATE UNIQUE INDEX PK_QOS_DATA ON "KORREKSJON"."QOS_DATA"(ID)
;
CREATE TABLE "KORREKSJON"."SCHEMA_VERSION"
(
   VERSION decimal(10) NOT NULL,
   MIGRATION_DATE timestamp NOT NULL
)
;
CREATE UNIQUE INDEX SYS_C004194 ON "KORREKSJON"."SCHEMA_VERSION"(VERSION)
;
CREATE TABLE "KORREKSJON"."SCHEMA_VERSION_INFO"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   INSTALLED timestamp,
   CURRENT_VERSION varchar2(255),
   PREVIOUS_VERSION varchar2(255),
   SCHEMA_OWNER varchar2(255)
)
;
CREATE UNIQUE INDEX PK_SCHEMA_VERSION_INFO ON "KORREKSJON"."SCHEMA_VERSION_INFO"(ID)
;
CREATE TABLE "KORREKSJON"."SEQUENCE_NUMBER"
(
   SEQ_KEY varchar2(255) PRIMARY KEY NOT NULL,
   SEQ_NUMBER varchar2(255)
)
;
CREATE UNIQUE INDEX PK_SEQUENCE_NUMBER ON "KORREKSJON"."SEQUENCE_NUMBER"(SEQ_KEY)
;
CREATE TABLE "KORREKSJON"."STATUS"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   IDX decimal(10),
   MESSAGE_CODE varchar2(255),
   MESSAGE_DETAIL_1 varchar2(255),
   MESSAGE_DETAIL_2 varchar2(255),
   MESSAGE_DETAIL_3 varchar2(255),
   STATUS_HISTORY decimal(19) NOT NULL,
   STATUS_CODE varchar2(255) NOT NULL,
   TIME_OCCURRED timestamp
)
;
CREATE UNIQUE INDEX PK_STATUS ON "KORREKSJON"."STATUS"(ID)
;
CREATE TABLE "KORREKSJON"."STATUS_HISTORY"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   ENTITY_KEY decimal(19),
   ENTITY_CLASS varchar2(255),
   CURRENT_STATUS_EVENT decimal(10)
)
;
CREATE UNIQUE INDEX PK_STATUS_HISTORY ON "KORREKSJON"."STATUS_HISTORY"(ID)
;
CREATE TABLE "KORREKSJON"."STATUS_MESSAGE"
(
   STATUS_ID decimal(19) NOT NULL,
   MESSAGE_CODE varchar2(255),
   DETAIL1 varchar2(255),
   DETAIL2 varchar2(255),
   DETAIL3 varchar2(255),
   LINE_NUMBER decimal(10)
)
;
CREATE TABLE "KORREKSJON"."WORK_ITEM"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   ENTITY_ID_LONG_PART decimal(19),
   ENTITY_ID_DISCRIMINATOR_PART decimal(19),
   PROCESSING_STATE decimal(10),
   CREATED_BY_SERVER_ID varchar2(255),
   PROCESSING_SERVER_ID varchar2(255),
   CREATED_TIME timestamp,
   START_TIME timestamp,
   FINISHED_TIME timestamp,
   EARLIEST_EXECUTION_TIME timestamp,
   THREAD_ID varchar2(255),
   ERROR_MESSAGE varchar2(3999),
   NUMBER_OF_RETRIES decimal(19),
   WORK_QUEUE decimal(19),
   WORK_QUEUE_NAME varchar2(255),
   ENTITY_DESCRIPTION varchar2(255)
)
;
ALTER TABLE "KORREKSJON"."WORK_ITEM"
ADD CONSTRAINT FK_WORK_ITEM_WORK_QUEUE
FOREIGN KEY (WORK_QUEUE)
REFERENCES "KORREKSJON"."WORK_QUEUE"(WORK_QUEUE)
;
CREATE INDEX WORK_ITEM_WORK_QUEUE_INDEX ON "KORREKSJON"."WORK_ITEM"(WORK_QUEUE)
;
CREATE UNIQUE INDEX PK_WORK_ITEM ON "KORREKSJON"."WORK_ITEM"(ID)
;
CREATE INDEX WORK_ITEM_INDEX2 ON "KORREKSJON"."WORK_ITEM"
(
  PROCESSING_STATE,
  EARLIEST_EXECUTION_TIME
)
;
CREATE TABLE "KORREKSJON"."WORK_QUEUE"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   ENTITY_SERVICE_NAME varchar2(255) NOT NULL,
   CONSUMER_ID varchar2(255) NOT NULL,
   STATUS decimal(10),
   START_TIME timestamp,
   SORT decimal(19),
   BESKRIVELSE varchar2(255),
   WORK_QUEUE_GROUP decimal(19)
)
;
ALTER TABLE "KORREKSJON"."WORK_QUEUE"
ADD CONSTRAINT FK_WORK_QUEUE_WORK_GROUP
FOREIGN KEY (WORK_QUEUE_GROUP)
REFERENCES "KORREKSJON"."WORK_QUEUE_GROUP"(WORK_QUEUE_GROUP)
;
CREATE UNIQUE INDEX SYS_C004202 ON "KORREKSJON"."WORK_QUEUE"(ENTITY_SERVICE_NAME)
;
CREATE UNIQUE INDEX PK_WORK_QUEUE ON "KORREKSJON"."WORK_QUEUE"(ID)
;
CREATE TABLE "KORREKSJON"."WORK_QUEUE_GROUP"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   GROUP_NAME varchar2(255) NOT NULL,
   SORT decimal(19) NOT NULL
)
;
CREATE UNIQUE INDEX SYS_C004204 ON "KORREKSJON"."WORK_QUEUE_GROUP"(GROUP_NAME)
;
CREATE UNIQUE INDEX PK_WORK_QUEUE_GROUP ON "KORREKSJON"."WORK_QUEUE_GROUP"(ID)
;
