ALTER TABLE KORR_TILSTANDER ADD CONSTRAINT UNIQUE_KORR_TILSTANDER unique (KORREKSJON_TYPE, SOURCE, BESTILLINGSNUMMER, BESTILLINGSDATO, CAUSE, STATUS);

ALTER TABLE KORREKSJON ADD CONSTRAINT UNIQUE_KORREKS unique (KORREKSJON_TYPE, SOURCE, BESTILLINGSNUMMER, BESTILLINGSDATO);
-- legg til nye kolonne i korreksjon
ALTER TABLE KORREKSJON ADD FULLMAKTSBREV_FIL_ID NUMBER(19,0) NULL ;
ALTER TABLE KORREKSJON ADD PURREBREV_FIL_ID NUMBER(19,0) NULL ;

-- legg til foreign key referanse
alter table KORREKSJON  add constraint FK_FULLMAKTSBREV foreign key (FULLMAKTSBREV_FIL_ID) REFERENCING FIL(ID);
alter table KORREKSJON  add constraint FK_PURREBREV foreign key (PURREBREV_FIL_ID) REFERENCING FIL(ID);
