-- legg til ny kolonne i korreksjon
ALTER TABLE KORREKSJON ADD OVERFORING_MED_FULLMAKT_ID NUMBER(19,0) NULL ;

-- legg til foreign key referanse
ALTER TABLE KORREKSJON ADD CONSTRAINT FK_OVERFORING_FULLMAKT foreign key (OVERFORING_MED_FULLMAKT_ID) REFERENCING KORREKSJON(ID);
